version: "3"
services:
  mongodb:
    image: bitnami/mongodb
    environment:
      MONGODB_ADVERTISED_HOSTNAME: mongodb
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_ROOT_PASSWORD: example
      MONGODB_REPLICA_SET_KEY: example
    ports:
      - "27017:27017"
  mongodb-1:
    image: bitnami/mongodb
    environment:
      MONGODB_ADVERTISED_HOSTNAME: mongodb-1
      MONGODB_REPLICA_SET_MODE: secondary
      MONGODB_INITIAL_PRIMARY_HOST: mongodb
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: 27017
      MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD: example
      MONGODB_REPLICA_SET_KEY: example
  mongodb-2:
    image: bitnami/mongodb
    environment:
      MONGODB_ADVERTISED_HOSTNAME: mongodb-2
      MONGODB_REPLICA_SET_MODE: arbiter
      MONGODB_INITIAL_PRIMARY_HOST: mongodb
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: 27017
      MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD: example
      MONGODB_REPLICA_SET_KEY: example
  redis:
    image: redis
    ports:
      - "6379:6379"
  nats-1:
    image: nats:alpine
    command: [ "-c","/etc/nats.conf" ]
    volumes:
      - "./nats-1.conf:/etc/nats.conf"
    ports:
      - "4222:4222"
  nats-2:
    image: nats:alpine
    command: [ "-c","/etc/nats.conf" ]
    volumes:
      - "./nats-2.conf:/etc/nats.conf"
    ports:
      - "4223:4222"
  nats-3:
    image: nats:alpine
    command: [ "-c","/etc/nats.conf" ]
    volumes:
      - "./nats-3.conf:/etc/nats.conf"
    ports:
      - "4224:4222"
