version: "3"
services:
  postgres:
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
  redis:
    image: redis
    ports:
      - "6379:6379"
  nats-1:
    image: nats:alpine
    command: [ "-c","/etc/nats.conf" ]
    volumes:
      - "./nats-1.conf:/etc/nats.conf"
    ports:
      - "4222:4222"
  nats-2:
    image: nats:alpine
    command: [ "-c","/etc/nats.conf" ]
    volumes:
      - "./nats-2.conf:/etc/nats.conf"
    ports:
      - "4223:4222"
  nats-3:
    image: nats:alpine
    command: [ "-c","/etc/nats.conf" ]
    volumes:
      - "./nats-3.conf:/etc/nats.conf"
    ports:
      - "4224:4222"
