#name: actions
#
#on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
#  release:
#    types: [ published ]
#
#jobs:
#
#  test:
#    name: Build
#    runs-on: ubuntu-latest
#    services:
#      postgres:
#        image: postgres:alpine
#        env:
#          POSTGRES_PASSWORD: postgres
#        options: >-
#          --health-cmd pg_isready
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 5
#        ports:
#          - 5432:5432
#
#    steps:
#      - uses: actions/setup-go@v2
#        with:
#          go-version: ^1.15
#
#      - uses: actions/checkout@v2
#
#      - name: Test
#        run: go test -v -coverprofile=profile.cov ./...
#        env:
#          GO111MODULE: on
#          DB_DSN: host=localhost user=postgres password=postgres dbname=postgres
#
#      - uses: shogo82148/actions-goveralls@v1
#        with:
#          path-to-profile: profile.cov