name: testing

on:
  push:
    branches: [ main ]

jobs:

  testing:
    name: Weplanx Go Testing
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
        ports:
          - 27017:27017

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15

      - name: Install dependencies
        run: go mod download

      - name: Run Unit tests
        run: go test -race -covermode atomic -coverprofile=covprofile ./...
        env:
          GO111MODULE: on
          TEST_DB: mongodb://root:example@127.0.0.1:27017/example?authSource=admin&directConnection=true

      - name: Install goveralls
        run: go install github.com/mattn/goveralls@latest

      - name: Send coverage
        run: goveralls -coverprofile=covprofile -service=github
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}