name: Testing

on:
  push:
    branches: [ main ]

jobs:

  testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: |
          docker-compose -f ".github/compose/docker-compose.yml" up -d

      - uses: actions/setup-go@v2
        with:
          go-version: ~1.20

      - run: |
          go mod tidy
          go test -race -covermode atomic -coverprofile=covprofile ./...
        env:
          GO111MODULE: on
          DATABASE_REDIS: redis://127.0.0.1:6379
          NATS_HOSTS: nats://127.0.0.1:4222,nats://127.0.0.1:4223,nats://127.0.0.1:4224
          NATS_NKEY: SUABEKK3NUTWCP3VMA2KFEKEOVAZHEK6R5LNIL66EWSRJC5Q37UD77FXII

      - name: PUSH COVERALLS
        run: |
          go install github.com/mattn/goveralls@latest
          goveralls -coverprofile=covprofile -service=github
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: PUSH FOSSAS
        run: "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"
