name: 单元测试

on:
  push:
    branches: [ main ]

jobs:

  testing:
    runs-on: ubuntu-latest
    services:
      nats-1:
        image: nats:alpine
        command:
          - --jetstream
          - --auth s3cr3t
          - --routes nats-route://nats-2:6222,nats-route://nats-3:6222
          - --cluster 0.0.0.0:6222
          - --cluster_name cluster
        ports:
          - 4222:4222
      nats-2:
        image: nats:alpine
        command:
          - --jetstream
          - --auth s3cr3t
          - --routes nats-route://nats-1:6222,nats-route://nats-3:6222
          - --cluster 0.0.0.0:6222
          - --cluster_name cluster
        ports:
          - 4223:4222
      nats-3:
        image: nats:alpine
        command:
          - --jetstream
          - --auth s3cr3t
          - --routes nats-route://nats-1:6222,nats-route://nats-2:6222
          - --cluster 0.0.0.0:6222
          - --cluster_name cluster
        ports:
          - 4224:4222
      mongodb:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
        ports:
          - 27017:27017

    steps:
      - name: 检出
        uses: actions/checkout@v2

      - name: 安装 Golang
        uses: actions/setup-go@v2
        with:
          go-version: ~1.17

      - name: 启动测试
        run: go test -race -covermode atomic -coverprofile=covprofile ./...
        env:
          GO111MODULE: on
          TEST_DB: mongodb://root:example@127.0.0.1:27017/example?authSource=admin&directConnection=true
          TEST_NATS: nats://127.0.0.1:4222,nats://127.0.0.1:4223,nats://127.0.0.1:4224
          TEST_NATS_TOKEN: s3cr3t

      - name: 推送覆盖率至 COVERALLS
        run: |
          go install github.com/mattn/goveralls@latest
          goveralls -coverprofile=covprofile -service=github
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 推送 FOSSAS
        run: "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"